language: generic
sudo: false
git:
  depth: 10

matrix:
  include:
    - os: linux
      env: VIM_VERSION=v7.4
    - os: linux
      env: VIM_VERSION=v8.0.0000
    - os: linux
      env: VIM_VERSION=master
    - os: osx

before_script:
  - git clone --depth 1 --single-branch https://github.com/syngan/vim-vimlint /tmp/vim-vimlint
  - git clone --depth 1 --single-branch https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser
  - git clone --depth 1 --single-branch https://github.com/kannokanno/vmock /tmp/vmock
  - git clone --depth 1 --single-branch --branch v1.5.2.1 https://github.com/thinca/vim-themis /tmp/vim-themis


install:
  - bash macros/install-vim.sh
  - export PATH=$HOME/vim/bin:$PATH

script:
  - uname -a
  - which -a vim
  - vim --cmd version --cmd quit
  - vim --cmd "try | helptags doc/ | catch | cquit | endtry" --cmd quit
  - git clean -f
  - sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -e EVL103=1 -e EVL102.l:_=1 -c func_abort=1 autoload plugin macros after
  - /tmp/vim-themis/bin/themis -r --runtimepath /tmp/vmock --reporter dot
  # check if both macros/generate-ftplugins.vim and after/ftplugin/ are updated
  - git clean -f
  - rm -rf after/ftplugin/
  - bash macros/generate-ftplugins.sh
  - bash -c '[[ -z $(git status -s) ]]'
