language: generic
sudo: false
git:
  depth: 10

matrix:
  include:
    - os: linux
      env:
        - VIM_VERSION=v7.4
        - RUN_VINT=true
    - os: linux
      env:
        - VIM_VERSION=v8.0.0000
        - RUN_VINT=true
    - os: linux
      env:
        - VIM_VERSION=master
        - RUN_VINT=true
    - os: osx
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew/
          - /usr/local/Homebrew/Library/Homebrew/vendor/
          - /usr/local/Homebrew/Library/Taps/
      before_cache:
        - brew cleanup

before_script:
  - git clone --depth 1 --single-branch https://github.com/syngan/vim-vimlint /tmp/vim-vimlint
  - git clone --depth 1 --single-branch https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser
  - git clone --depth 1 --single-branch https://github.com/kannokanno/vmock /tmp/vmock
  - git clone --depth 1 --single-branch --branch v1.5.2.1 https://github.com/thinca/vim-themis /tmp/vim-themis

addons:
  homebrew:
    packages:
      - macvim
    update: true

install:
  - bash macros/install-vim.sh
  - export PATH=$HOME/vim/bin:$PATH
  - if [ "$RUN_VINT" ]; then pip install --user --upgrade vim-vint pathlib enum34 typing; fi

script:
  - uname -a
  - which -a vim
  - vim --cmd version --cmd quit
  - vim --cmd "try | helptags doc/ | catch | cquit | endtry" --cmd quit
  - git clean -f
  - if [ "$RUN_VINT" ]; then python --version; fi
  - if [ "$RUN_VINT" ]; then vint autoload plugin macros after; fi
  - /tmp/vim-themis/bin/themis -r --runtimepath /tmp/vmock --reporter dot
  # check if both macros/generate-ftplugins.vim and after/ftplugin/ are updated
  - git clean -f
  - rm -rf after/ftplugin/
  - bash macros/generate-ftplugins.sh
  - bash -c '[[ -z $(git status -s) ]]'
