# my dotbot base configuration
- defaults:
    link:
      create: true
      relink: true

- shell:
    - [mkdir -p ~/.config]
    - [mkdir -p ~/.vim]

- link:
    ~/.dotfiles: ''

# executable
- shell:
    - [mkdir -p ~/bin]

- shell:
    - [git submodule update --init --recursive, Installing submodules]

# Clean symlinks which have moved
- clean: ['~', '~/.config/']
